import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, mkdirSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import AdmZip from "adm-zip";

const __dirname = dirname(fileURLToPath(import.meta.url));

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const outdir = prod ? "dist" : ".";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: `${outdir}/main.js`,
	loader: {
		".tiktoken": "text",
		".noindex": "text",
		".node": "binary",
	},
	jsxSideEffects: true, // Can keep 'unused' imports
});

if (prod) {
	mkdirSync(resolve(__dirname, "dist"), { recursive: true });
	await context.rebuild();
	copyFileSync(
		resolve(__dirname, "manifest.json"),
		resolve(__dirname, "dist/manifest.json"),
	);
	copyFileSync(
		resolve(__dirname, "styles.css"),
		resolve(__dirname, "dist/styles.css"),
	);
	const zip = new AdmZip();
	zip.addLocalFile(resolve(__dirname, "dist/main.js"));
	zip.addLocalFile(resolve(__dirname, "dist/manifest.json"));
	zip.addLocalFile(resolve(__dirname, "dist/styles.css"));
	zip.writeZip(resolve(__dirname, "dist/obsidian-github-copilot.zip"));
	console.log(
		"Packaged: dist/main.js, dist/manifest.json, dist/styles.css, dist/obsidian-github-copilot.zip",
	);
	process.exit(0);
} else {
	await context.watch();
}
